[tool.poetry]
name = "discord-rss-bot"
version = "0.1.0"
description = "RSS bot for Discord"
authors = ["Joakim Hellsén <tlovinator@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
reader = "^2.9"
typer = {extras = ["all"], version = "^0.4.0"}
dhooks = "^1.1.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
