[tool.poetry]
name = "discord-rss-bot"
version = "0.1.0"
description = "RSS bot for Discord"
authors = ["Joakim Hellsén <tlovinator@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
reader = "^2.6"
typer = "^0.4.0"
dhooks = "^1.1.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
bandit = "^1.7.1"
flake8 = "^4.0.1"
mypy = "^0.910"
black = {version = "^21.12b0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
