[tool.poetry]
name = "discord-rss-bot"
version = "0.1.0"
description = "RSS bot for Discord"
authors = ["Joakim Hellsén <tlovinator@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
reader = "^3.3"
discord-webhook = "^1.0.0"
platformdirs = "^2.6.2"
fastapi = "^0.89.0"
uvicorn = { extras = ["standard"], version = "^0.20.0" }
jinja2 = "^3.1.2"
apscheduler = "^3.9.1.post1"
python-multipart = "^0.0.5"
python-dotenv = "^0.21.0"
tomlkit = "^0.11.6"
markdownify = "^0.11.6"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
httpx = "^0.23.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.black]
line-length = 120
target-version = ["py311"]
