[tool.poetry]
name = "discord-rss-bot"
version = "0.2.0"
description = "RSS bot for Discord"
authors = ["Joakim Hellsén <tlovinator@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
reader = "^3.4"
discord-webhook = "^1.0.0"
platformdirs = "^2.6.2"
fastapi = "^0.90.0"
uvicorn = { extras = ["standard"], version = "^0.20.0" }
jinja2 = "^3.1.2"
apscheduler = "^3.10.0"
python-multipart = "^0.0.5"
python-dotenv = "^0.21.1"
tomlkit = "^0.11.6"
beautifulsoup4 = "^4.11.2"
lxml = "^4.9.2"
httpx = "^0.23.3"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
djlint = "^1.19.13"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.black]
line-length = 120
target-version = ["py311"]

[tool.djlint]
ignore = "D004,D018,J018,T001"
profile = "jinja"
max_line_length = 120
format_attribute_template_tags = true
