[tool.poetry]
name = "discord-rss-bot"
version = "0.1.0"
description = "RSS bot for Discord"
authors = ["Joakim Hellsén <tlovinator@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
reader = "^3.2"
typer = { extras = ["all"], version = "^0.7.0" }
discord-webhook = "^1.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
