# Generated by Django 5.2.5 on 2025-08-19 02:23
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("feed", models.TextField()),
                ("title", models.TextField()),
                ("link", models.TextField()),
                ("updated", models.DateTimeField()),
                ("author", models.TextField()),
                ("published", models.DateTimeField()),
                ("summary", models.TextField()),
                ("content", models.TextField()),
                ("enclosures", models.TextField()),
                ("source", models.TextField()),
                ("original_feed", models.TextField()),
                ("data_hash", models.BinaryField()),
                ("data_hash_changed", models.IntegerField()),
                ("read", models.IntegerField()),
                ("read_modified", models.DateTimeField()),
                ("important", models.IntegerField()),
                ("important_modified", models.DateTimeField()),
                ("added_by", models.TextField()),
                ("last_updated", models.DateTimeField()),
                ("first_updated", models.DateTimeField()),
                ("first_updated_epoch", models.DateTimeField()),
                ("feed_order", models.IntegerField()),
                ("recent_sort", models.IntegerField()),
                ("sequence", models.BinaryField()),
            ],
            options={
                "db_table": "entries",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EntryTag",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("feed", models.TextField()),
                ("key", models.TextField()),
                ("value", models.TextField()),
            ],
            options={
                "db_table": "entry_tags",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Feed",
            fields=[
                ("url", models.TextField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("link", models.TextField()),
                ("updated", models.DateTimeField()),
                ("author", models.TextField()),
                ("subtitle", models.TextField()),
                ("version", models.TextField()),
                ("user_title", models.TextField()),
                ("caching_info", models.TextField()),
                ("data_hash", models.BinaryField()),
                ("stale", models.IntegerField()),
                ("updates_enabled", models.IntegerField()),
                ("update_after", models.DateTimeField()),
                ("last_retrieved", models.DateTimeField()),
                ("last_updated", models.DateTimeField()),
                ("added", models.DateTimeField()),
                ("last_exception", models.TextField()),
            ],
            options={
                "db_table": "feeds",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FeedTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feed", models.TextField()),
                ("key", models.TextField()),
                ("value", models.TextField()),
            ],
            options={
                "db_table": "feed_tags",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Webhook",
            fields=[
                ("url", models.TextField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("channel", models.TextField()),
                ("user", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "webhooks",
                "managed": False,
            },
        ),
    ]
