# Generated by Django 5.0.4 on 2024-05-05 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LemonEntry',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('feed', models.TextField()),
                ('title', models.TextField()),
                ('link', models.TextField()),
                ('updated', models.TextField()),
                ('author', models.TextField()),
                ('published', models.TextField()),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('enclosures', models.TextField()),
                ('original_feed', models.TextField()),
                ('data_hash', models.TextField()),
                ('data_hash_changed', models.TextField()),
                ('read', models.TextField()),
                ('read_modified', models.TextField()),
                ('important', models.TextField()),
                ('important_modified', models.TextField()),
                ('added_by', models.TextField()),
                ('last_updated', models.TextField()),
                ('first_updated', models.TextField()),
                ('first_updated_epoch', models.TextField()),
                ('feed_order', models.TextField()),
                ('recent_sort', models.TextField()),
                ('sequence', models.TextField()),
            ],
            options={
                'db_table': 'entries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LemonFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('title', models.TextField()),
                ('link', models.TextField()),
                ('updated', models.TextField()),
                ('author', models.TextField()),
                ('subtitle', models.TextField()),
                ('version', models.TextField()),
                ('user_title', models.TextField()),
                ('http_etag', models.TextField()),
                ('http_last_modified', models.TextField()),
                ('data_hash', models.TextField()),
                ('stale', models.TextField()),
                ('updates_enabled', models.TextField()),
                ('last_updated', models.TextField()),
                ('added', models.TextField()),
                ('last_exception', models.TextField()),
            ],
            options={
                'db_table': 'feeds',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LemonFeedTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed', models.TextField()),
                ('key', models.TextField()),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'feed_tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LemonGlobalTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'global_tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MessageCustomization',
            fields=[
                ('feed_url', models.TextField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_message', models.TextField(default='{{entry_title}}\n{{entry_link}}')),
                ('should_be_embed', models.BooleanField(default=False)),
                ('custom_embed_title', models.TextField(default='{{entry_title}}')),
                ('custom_embed_description', models.TextField(default='{{entry_link}}')),
                ('custom_embed_color', models.TextField(default='#ecff80')),
                ('custom_embed_author_name', models.TextField(default='')),
                ('custom_embed_author_url', models.TextField(default='')),
                ('custom_embed_author_icon_url', models.TextField(default='')),
                ('custom_embed_image_url', models.TextField(default='{{image_1}}')),
                ('custom_embed_thumbnail_url', models.TextField(default='')),
                ('custom_embed_footer_text', models.TextField(default='')),
                ('custom_embed_footer_icon_url', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('url', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='BlacklistAuthor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.TextField(primary_key=True, serialize=False)),
                ('blacklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.blacklist')),
            ],
        ),
        migrations.CreateModel(
            name='BlacklistContent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(primary_key=True, serialize=False)),
                ('blacklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.blacklist')),
            ],
        ),
        migrations.CreateModel(
            name='BlacklistSummary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField(primary_key=True, serialize=False)),
                ('blacklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.blacklist')),
            ],
        ),
        migrations.CreateModel(
            name='BlacklistTitle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(primary_key=True, serialize=False)),
                ('blacklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.blacklist')),
            ],
        ),
        migrations.CreateModel(
            name='WhitelistAuthor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.TextField(primary_key=True, serialize=False)),
                ('whitelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.whitelist')),
            ],
        ),
        migrations.CreateModel(
            name='WhitelistContent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(primary_key=True, serialize=False)),
                ('whitelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.whitelist')),
            ],
        ),
        migrations.CreateModel(
            name='WhitelistSummary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField(primary_key=True, serialize=False)),
                ('whitelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.whitelist')),
            ],
        ),
        migrations.CreateModel(
            name='WhitelistTitle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(primary_key=True, serialize=False)),
                ('whitelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.whitelist')),
            ],
        ),
    ]
