# Generated by Django 5.0.6 on 2024-05-16 02:35
from __future__ import annotations

from typing import TYPE_CHECKING

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models

if TYPE_CHECKING:
    from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    initial = True

    dependencies: list[tuple[str, str]] = []

    operations: list[Operation] = [
        migrations.CreateModel(
            name="Blacklist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="The time the blacklist was created."),
                ),
                ("feed_url", models.TextField(help_text="The URL of the feed to blacklist.")),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="FeedInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="The time the info was created.")),
                ("feed_url", models.TextField(help_text="The URL of the feed to display the info for.")),
                (
                    "markdown",
                    models.TextField(
                        blank=True,
                        help_text="The markdown to display for the feed.",
                        verbose_name="Markdown",
                    ),
                ),
                (
                    "html",
                    models.TextField(
                        blank=True,
                        help_text="The HTML to display for the feed. This is generated from the markdown.",
                        verbose_name="HTML",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="MessageCustomization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("feed_url", models.TextField(help_text="The URL of the feed to customize the message for.")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time the message customization was created.",
                    ),
                ),
                (
                    "custom_message",
                    models.TextField(default="{{entry_title}}\n{{entry_link}}", help_text="The message to send."),
                ),
                (
                    "should_be_embed",
                    models.BooleanField(default=False, help_text="Whether the message should be an embed."),
                ),
                (
                    "custom_embed_title",
                    models.TextField(default="{{entry_title}}", help_text="The title of the embed."),
                ),
                (
                    "custom_embed_description",
                    models.TextField(default="{{entry_link}}", help_text="The description of the embed."),
                ),
                ("custom_embed_color", models.TextField(default="#ecff80", help_text="The color of the embed.")),
                ("custom_embed_author_name", models.TextField(default="", help_text="The author of the embed.")),
                ("custom_embed_author_url", models.TextField(default="", help_text="The author URL of the embed.")),
                (
                    "custom_embed_author_icon_url",
                    models.TextField(default="", help_text="The author icon URL of the embed."),
                ),
                (
                    "custom_embed_image_url",
                    models.TextField(default="{{image_1}}", help_text="The image URL of the embed."),
                ),
                (
                    "custom_embed_thumbnail_url",
                    models.TextField(default="", help_text="The thumbnail URL of the embed."),
                ),
                ("custom_embed_footer_text", models.TextField(default="", help_text="The footer text of the embed.")),
                (
                    "custom_embed_footer_icon_url",
                    models.TextField(default="", help_text="The footer icon URL of the embed."),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Webhook",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="The time the webhook was created.")),
                ("name", models.TextField(help_text="The name of the webhook. This is used to identify the webhook.")),
                (
                    "url",
                    models.TextField(help_text="The URL of the webhook. This is where the feed updates are sent to."),
                ),
                ("is_deleted", models.BooleanField(default=False, help_text="Whether the webhook is soft-deleted.")),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Whitelist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("feed_url", models.TextField(help_text="The URL of the feed to whitelist.")),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="BlacklistAuthor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time the author was added to the blacklist.",
                    ),
                ),
                ("author", models.TextField(help_text="Author to blacklist.")),
                (
                    "blacklist",
                    auto_prefetch.ForeignKey(
                        help_text="The blacklist to add the author to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authors",
                        related_query_name="author",
                        to="feeds.blacklist",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="BlacklistContent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time the content was added to the blacklist.",
                    ),
                ),
                ("content", models.TextField(help_text="Content to blacklist.")),
                (
                    "blacklist",
                    auto_prefetch.ForeignKey(
                        help_text="The blacklist to add the content to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        related_query_name="content",
                        to="feeds.blacklist",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="BlacklistSummary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time the summary was added to the blacklist.",
                    ),
                ),
                ("summary", models.TextField(help_text="Summary to blacklist.")),
                (
                    "blacklist",
                    auto_prefetch.ForeignKey(
                        help_text="The blacklist to add the summary to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        related_query_name="summary",
                        to="feeds.blacklist",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="BlacklistTitle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="The time the title was added to the blacklist."),
                ),
                ("title", models.TextField(help_text="Title to blacklist.")),
                (
                    "blacklist",
                    auto_prefetch.ForeignKey(
                        help_text="The blacklist to add the title to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="titles",
                        related_query_name="title",
                        to="feeds.blacklist",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="WhitelistAuthor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time the author was added to the whitelist.",
                    ),
                ),
                ("author", models.TextField(help_text="Author to whitelist.")),
                (
                    "whitelist",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authors",
                        to="feeds.whitelist",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="WhitelistContent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time the content was added to the whitelist.",
                    ),
                ),
                ("content", models.TextField(help_text="Content to whitelist.")),
                (
                    "whitelist",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="feeds.whitelist",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="WhitelistSummary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time the summary was added to the whitelist.",
                    ),
                ),
                ("summary", models.TextField(help_text="Summary to whitelist.")),
                (
                    "whitelist",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="feeds.whitelist",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="WhitelistTitle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="The time the title was added to the whitelist."),
                ),
                ("title", models.TextField(help_text="Title to whitelist.")),
                (
                    "whitelist",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="titles",
                        to="feeds.whitelist",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
