# Generated by Django 5.0.6 on 2024-05-09 15:20
from __future__ import annotations

from typing import TYPE_CHECKING

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models

if TYPE_CHECKING:
    from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies: list[tuple[str, str]] = [
        ("feeds", "0001_initial"),
    ]

    operations: list[Operation] = [
        migrations.AlterModelOptions(
            name="blacklist",
            options={"base_manager_name": "prefetch_manager"},
        ),
        migrations.AlterModelOptions(
            name="blacklistauthor",
            options={"base_manager_name": "prefetch_manager"},
        ),
        migrations.AlterModelOptions(
            name="blacklistcontent",
            options={"base_manager_name": "prefetch_manager"},
        ),
        migrations.AlterModelOptions(
            name="blacklistsummary",
            options={"base_manager_name": "prefetch_manager"},
        ),
        migrations.AlterModelOptions(
            name="blacklisttitle",
            options={"base_manager_name": "prefetch_manager"},
        ),
        migrations.AlterModelOptions(
            name="lemonentry",
            options={"base_manager_name": "prefetch_manager", "managed": False, "ordering": ["-read_modified"]},
        ),
        migrations.AlterModelOptions(
            name="lemonfeed",
            options={"base_manager_name": "prefetch_manager", "managed": False, "ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="lemonfeedtags",
            options={"base_manager_name": "prefetch_manager", "managed": False},
        ),
        migrations.AlterModelOptions(
            name="lemonglobaltags",
            options={"base_manager_name": "prefetch_manager", "managed": False},
        ),
        migrations.AlterModelOptions(
            name="messagecustomization",
            options={"base_manager_name": "prefetch_manager"},
        ),
        migrations.AlterModelOptions(
            name="webhook",
            options={"base_manager_name": "prefetch_manager"},
        ),
        migrations.AlterModelOptions(
            name="whitelist",
            options={"base_manager_name": "prefetch_manager"},
        ),
        migrations.AlterModelOptions(
            name="whitelistauthor",
            options={"base_manager_name": "prefetch_manager"},
        ),
        migrations.AlterModelOptions(
            name="whitelistcontent",
            options={"base_manager_name": "prefetch_manager"},
        ),
        migrations.AlterModelOptions(
            name="whitelistsummary",
            options={"base_manager_name": "prefetch_manager"},
        ),
        migrations.AlterModelOptions(
            name="whitelisttitle",
            options={"base_manager_name": "prefetch_manager"},
        ),
        migrations.AlterModelManagers(
            name="blacklist",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="blacklistauthor",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="blacklistcontent",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="blacklistsummary",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="blacklisttitle",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="messagecustomization",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="webhook",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="whitelist",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="whitelistauthor",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="whitelistcontent",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="whitelistsummary",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="whitelisttitle",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="blacklistauthor",
            name="blacklist",
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="feeds.blacklist"),
        ),
        migrations.AlterField(
            model_name="blacklistcontent",
            name="blacklist",
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="feeds.blacklist"),
        ),
        migrations.AlterField(
            model_name="blacklistsummary",
            name="blacklist",
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="feeds.blacklist"),
        ),
        migrations.AlterField(
            model_name="blacklisttitle",
            name="blacklist",
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="feeds.blacklist"),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="name",
            field=models.TextField(help_text="The name of the webhook. This is used to identify the webhook."),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="url",
            field=models.TextField(help_text="The URL of the webhook. This is where the feed updates are sent to."),
        ),
    ]
